# Generated by Django 4.0 on 2022-01-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
