# Generated by Django 4.0 on 2022-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
